### ISSUE TITLE
dropdown not maintaining state and actually not updating value

### ISSUE THREAD

**Issue by bootnumlock** [mzajkowski/umbraco-image-crop-picker#6]
Marcin,
i feel like you made a special v7 version of this for me... i thought it was working, but apparently it is not. The dropdown populates, but it does not remember what was selected, nor actually set a value. 

i wish i were smarter, but alas, i need your help :(

**Comment by mzajkowski** [comment]
Hey @bootnumlock! I do apologize for missing it, didn't see the notifications till now. Chase me on Twitter next time ;) We've done an upgrade for v8 and we've discovered there was an issue with the package and its build. I can try to generate you a new version of it for v7.

Is it still something that you need somewhere?

**Comment by bootnumlock** [comment]
Would LOVE a fix!

Thanks!

**Comment by mzajkowski** [comment]
Hey @bootnumlock! The issue was fixed for both: v7 and v8 builds. I've released path releases:

- 1.0.1 (for v7)
- 2.0.1 (for v8)

after great bug fixes from @aochmann. They are both available on NuGet and Our. Please give it a spin and test if it fixes your issue! Closing it for now.
